# Generated by Django 3.0.3 on 2020-02-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('isBeingLoaned', models.TextField()),
                ('owner', models.CharField(max_length=120)),
                ('dueDate', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
