# Generated by Django 3.0.3 on 2020-02-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200209_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='dueDate',
            new_name='daysLeft',
        ),
        migrations.AlterField(
            model_name='items',
            name='isBeingLoaned',
            field=models.BooleanField(),
        ),
    ]
