# Generated by Django 3.0.3 on 2020-02-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200209_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='isBeingLoaned',
            new_name='currentlyOut',
        ),
    ]
