# Generated by Django 3.0.3 on 2020-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200209_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='willingtoTravel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
